"""
ONNX-based AR Transformer engine for serverless (Vercel) inference.

Requires (generated by scripts/export_onnx.py):
    deploy/model.onnx
"""
import os
import numpy as np

ROOT        = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_INT8_PATH  = os.path.join(ROOT, "deploy", "model_int8.onnx")
_FP32_PATH  = os.path.join(ROOT, "deploy", "model.onnx")
MODEL_PATH  = _INT8_PATH if os.path.exists(_INT8_PATH) else _FP32_PATH

from utils.constants import MEMORY, INPUT_DIM, NUM_CLASSES_ALL, CHORD_CLASSES_ALL, TEMPERATURE

# base_engine.py is gitignored on Vercel (not needed there); guard the import.
try:
    from engines.base_engine import BaseChordEngine as _Base
except ImportError:
    _Base = object


def softmax(x):
    e = np.exp(x - np.max(x))
    return e / e.sum()


class ONNXTransformerEngine:
    """Stateless chord predictor — one ONNX session, one call per beat."""

    def __init__(self):
        import onnxruntime as ort

        opts = ort.SessionOptions()
        opts.inter_op_num_threads = 2
        opts.intra_op_num_threads = 2
        opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL

        self.session = ort.InferenceSession(
            MODEL_PATH,
            sess_options = opts,
            providers    = ["CPUExecutionProvider"],
        )

    def predict(self, history: np.ndarray) -> str:
        """
        Args:
            history: float32 [MEMORY, INPUT_DIM]
        Returns:
            chord name string e.g. 'C:maj', 'G:min7', 'N'
        """
        input_seq = history[np.newaxis, :, :].astype(np.float32)  # [1, MEMORY, INPUT_DIM]

        (logits,) = self.session.run(["logits"], {"input_seq": input_seq})
        logits = logits[0]  # [NUM_CLASSES]

        probs    = softmax(logits / TEMPERATURE).astype(np.float64)
        probs   /= probs.sum()
        pred_idx = np.random.choice(NUM_CLASSES_ALL, p=probs)
        return str(CHORD_CLASSES_ALL[pred_idx])


class ONNXChordEngine(_Base):
    """
    Drop-in replacement for ARTransformerEngine.
    Uses ONNXTransformerEngine for fast inference (~50 ms vs ~600 ms),
    so the predicted chord arrives in time to play on beat 5 rather than beat 9.
    """

    def __init__(self, tempo):
        super().__init__(tempo)
        self._onnx = ONNXTransformerEngine()

    def reset(self):
        self.history = np.zeros((0, INPUT_DIM))

    def process_beat(self, notes_played, beat_start_time, beat_index):
        padded = self.build_history(notes_played, beat_start_time, beat_index)
        chord_name = self._onnx.predict(padded.astype(np.float32))
        self.history = padded[-MEMORY:]
        return chord_name, self.beat_duration
