"""
Web-compatible loop lookup — pure numpy, no sklearn NearestNeighbors.

Uses data/lpd/nn_web.npz (generated by scripts/compress_nn.py).
Replaces the 192 MB nn.joblib with a ~3 MB compressed file.
"""
import os
import numpy as np
def softmax(x):
    e = np.exp(x - np.max(x))
    return e / e.sum()

ROOT         = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB_NPZ_PATH = os.path.join(ROOT, "deploy", "nn_web.npz")

from utils.constants import TEMPERATURE, STEPS_PER_BAR


def _groove(melody: np.ndarray) -> np.ndarray:
    """Binary activity mask: 1 where a note is present, 0 where silent (-1)."""
    return (np.asarray(melody, dtype=np.float32) != -1).astype(np.float32)


class WebLoopLookup:
    """Lazy-loaded; thread-safe after __init__."""

    def __init__(self, path: str = WEB_NPZ_PATH):
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"{path} not found — run  python scripts/compress_nn.py  first."
            )
        data          = np.load(path)
        self.features = data["features"]   # [N, 16] float32
        self.drums    = data["drums"]      # [N, 16, 128] uint8
        self.piano    = data["piano"]      # [N, 16, 8]   int8
        self.guitar   = data["guitar"]     # [N, 16, 8]   int8
        self.bass     = data["bass"]       # [N, 16, 1]   int8
        self._n       = len(self.features)
        # Only search patterns that have at least kick, snare, or hi-hat —
        # silent/rest segments in the dataset produce all-zero grooves that
        # win nearest-neighbour by default and yield no audible output.
        drum_active = data["drums"][:, :, [35, 36, 38, 40, 42, 44, 46]].any(axis=(1, 2))
        self._active_idx = np.where(drum_active)[0]

    def get_loops(self, melody, top_k: int = 10) -> dict:
        """
        Args:
            melody: array-like of length STEPS_PER_BAR (MIDI notes, -1 = silent)

        Returns:
            dict with keys 'drums', 'piano', 'guitar', 'bass',
            each a Python list suitable for JSON serialisation.
        """
        query          = _groove(melody)                                         # [16]
        active_feats   = self.features[self._active_idx]                         # [M, 16]
        dists          = np.abs(active_feats - query).sum(axis=1)               # [M]

        k       = min(top_k, len(self._active_idx))
        top_pos = np.argpartition(dists, k - 1)[:k]
        top_d   = dists[top_pos]

        logits  = -top_d / max(TEMPERATURE, 1e-6)
        probs   = softmax(logits).astype(np.float64)
        probs  /= probs.sum()

        chosen  = self._active_idx[top_pos[np.random.choice(k, p=probs)]]

        return {
            "drums":  self.drums[chosen].tolist(),
            "piano":  self.piano[chosen].tolist(),
            "guitar": self.guitar[chosen].tolist(),
            "bass":   self.bass[chosen].tolist(),
        }
